POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"frank",
    "lastName":"hilbert",
    "email":"f@gmail.com",
    "password":"Tr123456",
    "bio":"cont",
    "image":"http://localhost:3000/images/frank.jpeg"
    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"catherine",
    "lastName":"hilbert",
    "email":"c@gmail.com",
    "password":"Tr123456",
    "bio":"cont",
        "image":"http://localhost:3000/images/cathy.jpeg"

    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"tom",
    "lastName":"hilbert",
    "email":"t@gmail.com",
    "password":"Tr123456",
    "isAdmin":1,
    "bio":"cont",
            "image":"http://localhost:3000/mages/tom.jpeg"

    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"denis",
    "lastName":"Wawrziczny",
    "email":"d@gmail.com",
    "password":"Tr123456",
    "isAdmin":0,
    "bio":"cont"
    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"remi",
    "lastName":"Wawrziczny",
    "email":"r@gmail.com",
    "password":"Tr123456",
    "isAdmin":1,
    "bio":"cont",
            "image":"http://localhost:3000/images/remi.jpeg"

    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"f@gmail.com",
    "password":"Tr123456"
    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"f@gmail.com",
    "password":"Tr123456"
    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"c@gmail.com",
    "password":"Tr123456"
    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"t@gmail.com",
    "password":"Tr123456"
    
}
###
GET  http://localhost:3000/api/auth/profile/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYzMzAxNjc5MSwiZXhwIjoxNjMzMTAzMTkxfQ.TNGvaAvq2CgF3mgXYMcabR02CFFRQGWYysF5DgUMGPg

###
PUT http://localhost:3000/api/auth/profile/1
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzE1MzYwMzEsImV4cCI6MTYzMTYyMjQzMX0.Uct-Ejp_rsTBaYIWoWYCCJkfuVOv5kET-n6EoArdKaU

{
        "bio":" je suis  de mon papa",
            "isAdmin":0,
             "image":"http://localhost:3000/images/denis.jpeg"


 
}


###
DELETE http://localhost:3000/api/auth/profile/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTYzMzAxOTUwNiwiZXhwIjoxNjMzMTA1OTA2fQ.CKZP29YSG7Vt7wwjvkknpo9A8B0M8NPR_NXK_iiaRNI
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "email":"fhilbert@gmail.com",
    "password":"Tr05072003"
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"f.hilbert@wanadoo.fr",
    "password":"Tr123456"
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"jeanfrancois@gmail.com",
    "password":"1234"
}
### ----------- POSTS
GET http://localhost:3000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzEwMjk4MDksImV4cCI6MTYzMTExNjIwOX0.sD6jFgcBiNoj4dmb_ZqK0yZv4H_8hoM5PonczpzAIwg

###
GET http://localhost:3000/api/posts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE

###
POST  http://localhost:3000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzE2MjY5MDYsImV4cCI6MTYzMTcxMzMwNn0.HQDxCyEOQ3pa-JoR8X6dAEQ9dmylh78ZSjkGmE5sarQ
Content-Type:application/json

{
        "content":" hier",
        "image":"",
        "UserId":"1"
        ""
 
}
###
DELETE http://localhost:3000/api/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpCJ9.eyJpYXQiOjE2MzA0ODU0MTgsImV4cCI6MTYzMDU3MTgxOH0.ERS-ZrkjHSxJHwvV6iWXv3YXPS1vR1sNpX-6adA7uQc
###


### --------------- COMMENTS
POST  http://localhost:3000/api/posts/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzA0ODkzMDMsImV4cCI6MTYzMDU3NTcwM30.LKT-FUiqbmE_lifedmE4-7nUQPpvdXnA6cDXp5fa0-w
Content-Type:application/json

{
        "comment":"je suis le troisieme commentaire",
        "PostId":3,
        "UserId":4
 
}
###
GET http://localhost:3000/api/posts/comments/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE

###
GET http://localhost:3000/api/posts/comments/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
###
DELETE http://localhost:3000/api/posts/comments/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpCJ9.eyJpYXQiOjE2MzA0ODU0MTgsImV4cCI6MTYzMDU3MTgxOH0.ERS-ZrkjHSxJHwvV6iWXv3YXPS1vR1sNpX-6adA7uQc
###
### --------------- LIKES
POST  http://localhost:3000/api/posts/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzA0ODkzMDMsImV4cCI6MTYzMDU3NTcwM30.LKT-FUiqbmE_lifedmE4-7nUQPpvdXnA6cDXp5fa0-w
Content-Type:application/json

{
        "valeur":1,
        "PostId":3,
        "UserId":3
 }
###
GET http://localhost:3000/api/posts/like/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
###
PUT http://localhost:3000/api/posts/like/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
Content-Type:application/json

{
        "valeur":,

 }



###
GET http://localhost:3000/api/posts/likes/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
###
DELETE http://localhost:3000/api/posts/likes/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpCJ9.eyJpYXQiOjE2MzA0ODU0MTgsImV4cCI6MTYzMDU3MTgxOH0.ERS-ZrkjHSxJHwvV6iWXv3YXPS1vR1sNpX-6adA7uQc
###







