POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"frank11",
    "lastName":"hilbert",
    "email":"frank6@gmail.com",
    "password":"Tr05072033",
    "bio":"cont"
    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "firstName":"frank11",
    "lastName":"hilbert",
    "email":"frank6@gmail.com",
    "password":"Tr05072033",
    "bio":"cont"
    
}
###
POST  http://localhost:3000/api/posts
Content-Type:application/json

{
    "idUsers":2,
    "content":"je suis un texte",
    "attachment":"image"
    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "email":"fhilbert@gmail.com",
    "password":"Tr05072003"
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"fhilbert@gmail.com",
    "password":"Tr05072003"
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"a",
    "password":"b"
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"jeanfrancois@gmail.com",
    "password":"1234"
}
###
#jean francois
POST  http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE5OTBjNDEwY2JmMzQzY2Y1MmI4OTgiLCJpYXQiOjE2MjkwNjU1ODUsImV4cCI6MTYyOTE1MTk4NX0.PdWsoJ6CPKwiSPThw5HVq1bq33a5rQ0Un2Tm1803vM0
Content-Type:application/json

{
    "sauce":{
        "userId":"1234567890",
        "name":"tabasco",
        "manufacturer":"kraft",
        "description": "bouteille",
        "mainPepper":"poivre",
        "imageUrl":"http://localhost:3000/images/tabasco.png",
        "heat":4,
        "likes":0,
        "dislikes":0,
        "usersLiked":[],
        "usersDisliked":[]
    }
}
###
GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE

###
POST http://localhost:3000/api/sauces/60fdd794447a6092baaf3466/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFhY2U5ZTBkYjM3YmUwZGFhZmQ0ODgiLCJpYXQiOjE2MjkxNjEzNTUsImV4cCI6MTYyOTI0Nzc1NX0.AwI0llwjzUkTj-Dq9515-IJkg4-DR5kOu6GxIvqtkRU
Content-Type:application/json

{
    "like": -1,
  "userId": "61000b346c8b4ae57b34cc54"
}
###
PUT http://localhost:3000/api/sauces/611ace8b0db37be0daafd485
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
Content-Type:application/json

{
    
    "manufacturer": "inconnuer"
}
###
DELETE http://localhost:3000/api/sauces/611ace8b0db37be0daafd485
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
Content-Type:application/json

























