POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"frank",
    "lastName":"hilbert",
    "email":"f@gmail.com",
    "password":"Tr123456",
    "bio":"cont",
    "photo":"http://localhost:3000/images/frank.jpeg"
    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"catherine",
    "lastName":"hilbert",
    "email":"c@gmail.com",
    "password":"Tr123456",
    "bio":"cont",
        "photo":"http://localhost:3000/images/cathy.jpeg"

    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"tom",
    "lastName":"hilbert",
    "email":"t@gmail.com",
    "password":"Tr123456",
    "isAdmin":1,
    "bio":"cont",
            "photo":"http://localhost:3000/mages/tom.jpeg"

    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"denis",
    "lastName":"Wawrziczny",
    "email":"d@gmail.com",
    "password":"Tr123456",
    "isAdmin":1,
    "bio":"cont",
            "photo":"http://localhost:3000/images/denis.jpeg"

    
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "firstName":"remi",
    "lastName":"Wawrziczny",
    "email":"r@gmail.com",
    "password":"Tr123456",
    "isAdmin":1,
    "bio":"cont",
            "photo":"http://localhost:3000/images/remi.jpeg"

    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"f@gmail.com",
    "password":"Tr123456"
    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"f@gmail.com",
    "password":"Tr123456"
    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"c@gmail.com",
    "password":"Tr123456"
    
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"t@gmail.com",
    "password":"Tr123456"
    
}
###
GET  http://localhost:3000/api/auth/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAyNDc3MDgsImV4cCI6MTYzMDMzNDEwOH0.xHcx9CRobM0SRuOxgGOtIiq-6QKlaZ_9jH9RekUNW3c

###
PUT http://localhost:3000/api/auth/profile/3
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzEyNzM1NzcsImV4cCI6MTYzMTM1OTk3N30.LtkaJ9ImNVW_mmFpceJY7dpi4qjoRLcpV_DEPoMNwdM

{
        "bio":" je suis le fils de mon papa",
 
}


###
DELETE http://localhost:3000/api/auth/profile/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpCJ9.eyJpYXQiOjE2MzA0ODU0MTgsImV4cCI6MTYzMDU3MTgxOH0.ERS-ZrkjHSxJHwvV6iWXv3YXPS1vR1sNpX-6adA7uQc
###
POST  http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "email":"fhilbert@gmail.com",
    "password":"Tr05072003"
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"f.hilbert@wanadoo.fr",
    "password":"Tr123456"
}
###
POST  http://localhost:3000/api/auth/login
Content-Type:application/json

{
    "email":"jeanfrancois@gmail.com",
    "password":"1234"
}
### ----------- POSTS
GET http://localhost:3000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzEwMjk4MDksImV4cCI6MTYzMTExNjIwOX0.sD6jFgcBiNoj4dmb_ZqK0yZv4H_8hoM5PonczpzAIwg

###
GET http://localhost:3000/api/posts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE

###
POST  http://localhost:3000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzA2MjIxMzEsImV4cCI6MTYzMDcwODUzMX0.zRNdU2zhiNE54bUXBnSoeCuW2iag5e4XCzx8bcN94OY
Content-Type:application/json

{
        "content":" hier",
        "image":"",
        "UserId":1
 
}
###
DELETE http://localhost:3000/api/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpCJ9.eyJpYXQiOjE2MzA0ODU0MTgsImV4cCI6MTYzMDU3MTgxOH0.ERS-ZrkjHSxJHwvV6iWXv3YXPS1vR1sNpX-6adA7uQc
###


### --------------- COMMENTS
POST  http://localhost:3000/api/posts/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzA0ODkzMDMsImV4cCI6MTYzMDU3NTcwM30.LKT-FUiqbmE_lifedmE4-7nUQPpvdXnA6cDXp5fa0-w
Content-Type:application/json

{
        "comment":"je suis le troisieme commentaire",
        "PostId":3,
        "UserId":4
 
}
###
GET http://localhost:3000/api/posts/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE

###
GET http://localhost:3000/api/posts/comments/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
###
DELETE http://localhost:3000/api/posts/comments/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpCJ9.eyJpYXQiOjE2MzA0ODU0MTgsImV4cCI6MTYzMDU3MTgxOH0.ERS-ZrkjHSxJHwvV6iWXv3YXPS1vR1sNpX-6adA7uQc
###
### --------------- LIKES
POST  http://localhost:3000/api/posts/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzA0ODkzMDMsImV4cCI6MTYzMDU3NTcwM30.LKT-FUiqbmE_lifedmE4-7nUQPpvdXnA6cDXp5fa0-w
Content-Type:application/json

{
        "valeur":1,
        "PostId":3,
        "UserId":1
 }
###
GET http://localhost:3000/api/posts/likes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE

###
GET http://localhost:3000/api/posts/likes/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
###
DELETE http://localhost:3000/api/posts/likes/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpCJ9.eyJpYXQiOjE2MzA0ODU0MTgsImV4cCI6MTYzMDU3MTgxOH0.ERS-ZrkjHSxJHwvV6iWXv3YXPS1vR1sNpX-6adA7uQc
###







#jean francois
POST  http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE5OTBjNDEwY2JmMzQzY2Y1MmI4OTgiLCJpYXQiOjE2MjkwNjU1ODUsImV4cCI6MTYyOTE1MTk4NX0.PdWsoJ6CPKwiSPThw5HVq1bq33a5rQ0Un2Tm1803vM0
Content-Type:application/json

{
    "sauce":{
        "userId":"1234567890",
        "name":"tabasco",
        "manufacturer":"kraft",
        "description": "bouteille",
        "mainPepper":"poivre",
        "imageUrl":"http://localhost:3000/images/tabasco.png",
        "heat":4,
        "likes":0,
        "dislikes":0,
        "usersLiked":[],
        "usersDisliked":[]
    }
}
###
GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE

###
POST http://localhost:3000/api/sauces/60fdd794447a6092baaf3466/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFhY2U5ZTBkYjM3YmUwZGFhZmQ0ODgiLCJpYXQiOjE2MjkxNjEzNTUsImV4cCI6MTYyOTI0Nzc1NX0.AwI0llwjzUkTj-Dq9515-IJkg4-DR5kOu6GxIvqtkRU
Content-Type:application/json

{
    "like": -1,
  "userId": "61000b346c8b4ae57b34cc54"
}
###
PUT http://localhost:3000/api/sauces/611ace8b0db37be0daafd485
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
Content-Type:application/json

{
    
    "manufacturer": "inconnuer"
}
###
DELETE http://localhost:3000/api/sauces/611ace8b0db37be0daafd485
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFiYjViOWNiYWUxZDAzYmNiMDRkMjYiLCJpYXQiOjE2MjkyMDc2NzAsImV4cCI6MTYyOTI5NDA3MH0.drRjVbFwsMEyZd9YPvXGncC2C4wUt-RsxEJs7DFn8sE
Content-Type:application/json

























